#!/bin/bash

set -e

(( EUID )) && echo "$(basename ${0}) must be run as root (or with sudo)" && exit 1

VERSION="0.6.14"

URL="https://kernel.ubuntu.com/~kernel-ppa/mainline"
DATA=/tmp/kumk
[[ ! $2 = *lowlatency* ]] && MODE="generic" ||  MODE="lowlatency"
TMP="${DATA}/tmp"
BIN="${DATA}/bin"

## set color
C_OFF="\033[0;0m"
C_GRE="\033[01;32m"
C_BLU="\033[01;34m"
C_YEL="\033[01;33m"
C_RED="\033[01;31m"
C_REDY="\033[01;33;41m"
C_REDW="\033[01;37;41m"
C_WHIT="\033[01;37m"
INFO=" ${C_YEL}*${C_WHIT}"
WARN=" ${C_GRE}*${C_YEL}"
WARNNS=" ${C_YEL}"
ERRO=" ${C_REDY}*${C_REDW}"
ERROS=" ${C_RED}*${C_YEL}"

##### localisation:
## 
set_locale(){
    case ${LANG} in
        'cs_CZ'|'cs_CZ.UTF-8')
            error_must_enter_version_as_second_parameter="ERROR: Je potřeba zadat číslo verze jako druhý parametr..."
            error_unknown_main_parameter="Neznámý hlavní parametr:"
            error_server_or_internet_not_available="Server ${URL_PING}, nebo internetové spojení není dostupné"
            help_show_available_versions="zobrazit dostupné verze"
            help_show_installed="zobrazit nainstalované"
            help_download_and_install="stáhnout a nainstalovat"
            help_download_only="pouze stáhnout"
            help_install_only="pouze nainstalovat"
            help_purge_kernel="odstranit jádro"
            help_sicherboot="nastavit výchozí pro sicherboot"
            help_information="Informace:"
            help_version="verze:"
            help_ver_ver="určuje verzi pro \"i, d, n, p, b\", nebo filtr pro \"s, l\""
            help_ver_latest="automaticky rozpoznat poslední stabilní verzi pro \"i\""
            help_ver_latest_rc="automaticky rozpoznat poslední rc verzi pro  \"i\""
            help_ver_norc="použitelné pouze při \"s\" k zakázání zobrazení rc verze"
            help_running_os="Běžící OS:"
            help_running_kernel="Běžící Jádro:"
            help_free_on="Volno v"
            help_upgrade="aktualizovat kumk z github"

            this_version_have_failed_build="Tato verze obsahuje neůspěšný build... Končím..."
            kernel_is_not_ready_yet="(zatím v přípravě)"
            this_version_not_ready_yet_switch_to_previous_yes_no="poslední jádro ${VER} zatím není připraveno, přepnout na předposlední ${VER_PREV}? [a/N] "
            downloading_ver="Stahuji ${VER}..."
            packages_for_ver_not_found_exiting="Balíček pro ${VER} nenalezen... Končím..."
            download_file_deb="Stahuji soubor: ${deb}..."
            download_file_deb_failed="Nepodařílo se stáhnout soubor: ${deb}... Končím..."
            in_system_is_installed_libc_ge_req_installing_normal="v systému je nainstalována libc >=${libc6_req}, instaluji normálně..."
            install_ver_yes_no="Instalovat ${VER}? [a/N] "
            installing_kernel_version_gt_51116_and_libc6_is_lt_req_install_via_workaround="instalovaná verze jádra je >5.11.16 a libc6 je <${libc6_req}, instaluju workaroundem..."
            install_workaround_depends_yes_no="instalace workaroundem požaduje doinstalovat chybějící závislosti: ${need_install_depends/ } [a/N] "
            installing_package="instaluji balíček"
            installing_only_unpacking_package="instaluji/rozbaluji_pouze balíček"
            installing_rest="instaluji zbylé:"
            and="a"
            installing_kernel_version_le_51116_install_normal="instalovaná verze jádra je <=5.11.16, instaluju normálně..."
            install_canceled="Instalace zrušena..."
            downloading_package_file_for_extracting_tools="Stahuji balíček ${file} z kterého vypreparuji nástroje:"
            unpacking_files="Rozbaluji soubory..."
            copy_to="Kopíruji do"
            replacing_binaries_in="nahrazuji binárky v"
            backup_previous_file_to="zálohuji původní soubor do"
            configuring_package_linux_header_ver_long_with_ignoring_depends_on_libc6_version="konfiguruji balíček linux-headers-${VER_LONG} s ingorováním závislostí na verzi libc6${ignore_libssl3}..."
            workarounding_depends_on_unavailable_libssl3_faking_to_libssl1="Obcházím závislost na nedostupném libssl3 falšováním na libssl1.1"
            removing_backup_of_previous_file="odstranuji zálohu původního souboru"
            package_ver_not_found="Žádný balíček verze ${VER} nebyl nalezen..."
            running="běžící"
            is_running_kernel_exiting="je běžící jádro... Končím..."
            set_ver_as_default_for_sicherboot="Nastavit ${VER} jako výchozí pro sicherboot? [a/N]"
            detect_new_id_via_bootctl="detekuji new ID nástrojem bootctl..."
            previous_detect_failed_try_default_efi_dir="předchozí detekce selhala, zkouším výchozí adresář /boot/efi..."
            not_detected_new_id_skipping_setting="nedetekovano new ID, preskakuji nastaveni..."
            ambiguous_detection_new_id_skipping_setting="nejistá detekce new ID, preskakuji nastaveni..."
            set_default_to="nastavuji výchozí na:"
            sicherboot_not_found_exiting="Sicherboot nenalezen... Končím..."
            sicherboot_kernel_not_found="Nenalezeno jádro ${VER} k nastavení pro sicherboot výchozí... Končím..."
            finish="Dokončeno..."
            check_for_kumk_new_version="Kontrola dostupnosti nové verze kumk..."
            no_new_version="nová verze nenalezena..."
            found_new_version_upgrade_me_ask="nalezena nová verze, mám se sám aktualizovat? [a/N] "
            upgrade_skipped="aktualizace přeskočena..."
            upgrading_myself="aktualizuji se..."
            problem_with_check_new_version="problém při zjišťování nové verze"
            disabling_config_sls="instaluji jádro >=5.17.4 v systému s gcc <11, zakazuji CONFIG_SLS (oprava pro sestavení DKMS modulů)"
        ;;
        *)
            error_must_enter_version_as_second_parameter="ERROR: Must enter version as second param..."
            error_unknown_main_parameter="ERROR: Unknown main parameter:"
            error_server_or_internet_not_available="Server ${URL_PING} or internet connection not available"
            help_show_available_versions="show available versions"
            help_show_installed="show installed"
            help_download_and_install="download and install"
            help_download_only="download only"
            help_install_only="install only"
            help_purge_kernel="purge kernel"
            help_sicherboot="set default for sicherboot"
            help_information="Information:"
            help_version="version:"
            help_ver_ver="specify version for \"i, d, n, p, b\" or filter for \"s, l\""
            help_ver_latest="auto detect latest stable version for \"i\""
            help_ver_latest_rc="auto detect latest rc version for \"i\""
            help_ver_norc="used only for \"s\" to disable show rc version"
            help_running_os="Running OS:"
            help_running_kernel="Running Kernel:"
            help_free_on="Free on"
            help_upgrade="upgrade kumk from github"

            this_version_have_failed_build="This version have failed build. Exiting..."
            kernel_is_not_ready_yet="(not ready yet)"
            this_version_not_ready_yet_switch_to_previous_yes_no="latest kernel ${VER} not ready yet, switch to previous latest ${VER_PREV}? [y/N] "
            downloading_ver="Downloading ${VER}..."
            packages_for_ver_not_found_exiting="Packages for ${VER} not found... Exiting..."
            download_file_deb="Downloading file: ${deb}..."
            download_file_deb_failed="Downloading file: ${deb} failed... Exiting..."
            in_system_is_installed_libc_ge_req_installing_normal="in system is installed libc >=${libc6_req}, installing normal..."
            install_ver_yes_no="Install ${VER}? [y/N] "
            installing_kernel_version_gt_51116_and_libc6_is_lt_req_install_via_workaround="installing kernel version >5.11.16 and libc6 is <${libc6_req}, installing via workaround..."
            install_workaround_depends_yes_no="installing via workaround need install missing dependencies: ${need_install_depends/ } [y/N] "
            installing_package="installing package"
            installing_only_unpacking_package="installing/only_unpacking package"
            installing_rest="installing rest:"
            and="and"
            installing_kernel_version_le_51116_install_normal="installing kernel version <=5.11.16, install normal..."
            install_canceled="Install canceled..."
            downloading_package_file_for_extracting_tools="Downloading package ${file} for extracting tools:"
            unpacking_files="Unpacking files..."
            copy_to="Copy to"
            replacing_binaries_in="replacing binaries in"
            backup_previous_file_to="backup previous file to"
            configuring_package_linux_header_ver_long_with_ignoring_depends_on_libc6_version="configuring package linux-headers-${VER_LONG} with ignoring depends on libc6${ignore_libssl3} version..."
            workarounding_depends_on_unavailable_libssl3_faking_to_libssl1="Workarounding depends on unavailable libssl3 faking to libssl1.1"
            removing_backup_of_previous_file="removing backup of previous file"
            package_ver_not_found="Package version ${VER} not found..."
            running="running"
            is_running_kernel_exiting="is running kernel... Exiting..."
            set_ver_as_default_for_sicherboot="Set ${VER} as default for sicherboot? [y/N]"
            detect_new_id_via_bootctl="detect new ID via tool bootctl..."
            previous_detect_failed_try_default_efi_dir="previous detect failed, trying default dir /boot/efi..."
            not_detected_new_id_skipping_setting="not detected new ID, skipping setting..."
            ambiguous_detection_new_id_skipping_setting="ambiguous detection of new ID, skipping setting..."
            set_default_to="set default to:"
            sicherboot_not_found_exiting="Sicherboot not found... Exiting..."
            sicherboot_kernel_not_found="Not found kernel ${VER} for sicherboot default setting... Exiting..."
            finish="Finish..."
            check_for_kumk_new_version="Checking kumk new version..."
            no_new_version="new version not found..."
            found_new_version_upgrade_me_ask="found new version, should I update myself? [y/N] "
            upgrade_skipped="upgrade skipped..."
            upgrading_myself="upgrading myself..."
            problem_with_check_new_version="problem when checking for a new version"
            disabling_config_sls="installing kernel >=5.17.4 in system with gcc <11, disabling CONFIG_SLS (fix for build DKMS modules)"
        ;;
    esac
}


## set colored echo's
einfo() {
    echo ""
    echo -e "$INFO $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

einfon() {
    echo ""
    echo -n -e "$INFO $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

ewarn() {
    echo -e "   $WARN $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

ewarnt() {
    echo -e "   \t$WARN $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

ewarntt() {
    echo -e "   \t\t$WARN $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

ewarnn() {
    echo -n -e "   $WARN $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

### without star
ewarnns() {
    echo -e "   $WARNNS $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

ewarny() {
    echo -e "\n   $WARN $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

eerrorsmall(){
    echo -e "   $ERROS $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

eerror() {
    echo -e "$ERRO $1${C_OFF}"
    if [ "$2" != "" ]; then echo "$1" >>$OUT/$2; fi
}

detect_arch(){
    arch_out="$(arch)"
    [[ $arch_out = x86_64 ]] && ARCH="amd64" || ARCH="i386"
}

check_url_available(){
    URL_PING="$(echo "${URL}" | sed 's#.*://##;s#/.*##')"
    ping -c1 ${URL_PING} &>/dev/null || {
        set_locale
        eerror "${error_server_or_internet_not_available}"
        exit
    }
}

download_kernel(){
    check_url_available
    ver_check_success="$(wget -q "${URL}/v${VER_NOZER:-${VER}}/HEADER.html" -O- | grep "${ARCH}/build succeeded" || true)"
    [[ ${ver_check_success} ]] || {
        set_locale
        ewarnn "${this_version_not_ready_yet_switch_to_previous_yes_no}"
        read -n1 answer; echo ""
        [[ "${answer}" = [y,Y,a,A] ]] && {
            VER="${VER_PREV}"
            VER_NOZER="${VER_PREV_NOZER}"
            set_locale
        } || {
            ewarn "${install_canceled}"
            exit
        }
    }

    mkdir -p ${TMP}
    header="${TMP}/${VER}-HEADER.html"
    wget -q "${URL}/v${VER_NOZER:-${VER}}/HEADER.html" -O ${header}

    if (grep -q -e "Build for ${ARCH} failed" -e "Test ${ARCH}/build failed" ${header}); then
        eerror "${this_version_have_failed_build}"
        exit
    else
        header_onever="$(grep ${ARCH}/linux.*_all.deb ${header} | tail -n1 | sed "s/_all.deb.*//;s/.*${VER}.*\.//")"
        debs=( $(grep ${ARCH}/linux ${header} | sed 's/deb">.*/deb/g;s/.*href="//' | grep -v BUILD | grep -e all -e ${MODE} | grep ${header_onever}) )
        einfo "${downloading_ver}"
        [[ $debs ]] || { eerror "${packages_for_ver_not_found_exiting}"; exit; }
        for deb in ${debs[@]}; do
            set_locale
            ewarn "${download_file_deb}"
            wget -q --continue --no-verbose --directory-prefix ${DATA}/${VER} "${URL}/v${VER_NOZER:-${VER}}/${deb}" || {
                eerror "${download_file_deb_failed}"
                exit
            }
        done
    fi
}

check_gcc(){
    which gcc &>/dev/null && GCC_VER="$(gcc -dumpversion)"
    [[ ${GCC_VER} -lt 11 ]] && {
        dpkg --compare-versions "${VER}" "ge" "5.17.4" && {
            DST="/usr/src/linux-headers-${VER_LONG}/include/config"
            ewarn "${disabling_config_sls}"
            [[ -f ${DST}/auto.conf.orig ]] || cp -a ${DST}/auto.conf ${DST}/auto.conf.orig
            sed 's/^CONFIG_SLS=/#&/' -i ${DST}/auto.conf
        } || true
    }
}

install_kernel(){
    einfon "${install_ver_yes_no}"
    read -n1 answer; echo ""
    if [[ "${answer}" = [y,Y,a,A] ]]; then 
        libc6_ver="$(dpkg -l libc6 2>/dev/null | grep libc6 | head -n1 | awk '{print $3}' | sed 's/-.*//')"
        libc6_req="$(dpkg-deb -f ${DATA}/${VER}/linux-header*${MODE}*.deb Depends | sed 's/.*libc6 (>= //;s/).*//')"
        set_locale

        if [[ ${libc6_ver//./,} -ge ${libc6_req//./,} ]]; then
            (dpkg --compare-versions "${VER}" "gt" "5.11.16") && ewarn "${in_system_is_installed_libc_ge_req_installing_normal}"
            dpkg -i ${DATA}/${VER}/*.deb >/dev/null
        else
            check_depends
            if (dpkg --compare-versions "${VER}" "gt" "5.11.16"); then
                ewarn "${installing_kernel_version_gt_51116_and_libc6_is_lt_req_install_via_workaround}"
                ewarn "${installing_package} $(basename $(ls ${DATA}/${VER}/linux-header*all*.deb))..."
                dpkg -i ${DATA}/${VER}/linux-header*all*.deb >/dev/null
                ewarn "${installing_only_unpacking_package} $(basename $(ls ${DATA}/${VER}/linux-header*${MODE}*.deb))..."
                dpkg --unpack ${DATA}/${VER}/linux-header*${MODE}*.deb >/dev/null
                do_copy_bin
                check_gcc
                do_config_pkg
                ewarn "${installing_rest}"
                ewarnt "$(basename $(ls ${DATA}/${VER}/linux-image*.deb))"
                ewarnt "$(basename $(ls ${DATA}/${VER}/linux-module*.deb))"
                dpkg -i ${DATA}/${VER}/linux-image*.deb ${DATA}/${VER}/linux-module*.deb >/dev/null
            else
                ewarn "${installing_kernel_version_le_51116_install_normal}"
                dpkg -i ${DATA}/${VER}/*.deb >/dev/null
            fi
        fi
    else
        ewarn "${install_canceled}"
        exit
    fi

    which sicherboot >/dev/null && sicherboot_set_default || true
}

check_depends(){
    depends_packages=( binutils )
    for package in ${depends_packages[@]}; do
        dpkg -l ${package} | grep -q '^ii' || need_install_depends+=" ${package}"
    done

    if [[ ${need_install_depends} ]]; then
        set_locale
        ewarnn "${install_workaround_depends_yes_no}"
        read -n1 answer; echo ""

        if [[ "${answer}" = [y,Y,a,A] ]]; then 
            apt-get update -qq >/dev/null && apt-get install -y ${need_install_depends} >/dev/null
        else
            ewarn "${install_canceled}"
            exit
        fi
    fi
}

do_get_bin(){
    SRC_VER="5.11.16-051116-generic"
    file="linux-headers-${SRC_VER}_5.11.16-051116.202104211235_amd64.deb"
    set_locale

    ewarnt "${downloading_package_file_for_extracting_tools}"
    ewarntt "fixdep, modpost, objtool, genksyms, sign-file..."
    wget -q https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.16/amd64/${file} -O "${TMP}/${file}"

    ewarnt "${unpacking_files}"
    ( ar --help | grep -q -m1 '\--output' ) && output="--output ${TMP}" || cd ${TMP}
    ar x ${output} "${TMP}/${file}"
    tar xf "${TMP}/data.tar.xz" --directory "${TMP}"
    ewarnt "${copy_to} ${BIN}:"
    for i in scripts/basic/fixdep tools/objtool/fixdep tools/bpf/resolve_btfids/fixdep scripts/mod/modpost tools/objtool/objtool scripts/genksyms/genksyms scripts/sign-file; do
        mkdir -p ${BIN}/${i%\/*}
        ewarntt "${i}..."
        cp -a  ${TMP}/usr/src/linux-headers-${SRC_VER}/${i} ${BIN}/${i}
    done
}

do_copy_bin(){
    VER_LONG=$(ls -d /usr/src/linux-headers-${VER/-rc/*rc}*${MODE} | sed 's/.*headers-//')
    set_locale
    DST="/usr/src/linux-headers-${VER_LONG}"
    ewarn "${replacing_binaries_in} ${DST}..."
    for i in scripts/basic/fixdep tools/objtool/fixdep tools/bpf/resolve_btfids/fixdep scripts/mod/modpost tools/objtool/objtool scripts/genksyms/genksyms scripts/sign-file; do
        [[ -f ${BIN}/${i} ]] || do_get_bin
        [[ -f ${DST}/${i}.orig ]] || { 
            [[ ${is_show_backup_previous_file_to} ]] || { ewarnt "${backup_previous_file_to} ${DST}:"; is_show_backup_previous_file_to="YES"; }
            ewarntt "${i}.orig"
            cp -a ${DST}/${i} ${DST}/${i}.orig
        }
    done
    cp -a "${BIN}/"* ${DST}
}

do_config_pkg(){
    dpkg --compare-versions "${VER}" "ge" "5.15.7" && {
        (dpkg -l libssl3 2>/dev/null | grep -q '^ii \+libssl3') || ignore_libssl3=",libssl3"
    }

    if (dpkg -l | grep linux-headers-${VER_LONG} | grep -q ^iU); then
        set_locale
        ewarn "${configuring_package_linux_header_ver_long_with_ignoring_depends_on_libc6_version}"
        dpkg --configure --ignore-depends=libc6${ignore_libssl3} linux-headers-${VER_LONG} >/dev/null
    else
        which dkms >/dev/null && do_dkms ${VER_LONG}
    fi

    sed "/Depends: linux-headers-${VER_LONG/-generic}, libc6/s/libc6 (>= 2...)/libc6 (>= ${libc6_ver})/" -i /var/lib/dpkg/status

    [[ ${ignore_libssl3} ]] && {
        ewarnt "${workarounding_depends_on_unavailable_libssl3_faking_to_libssl1}"
        sed "/Depends: linux-headers-${VER_LONG/-generic}.*libssl3/s/libssl3[^)]*)/libssl1.1 (>= 1.1.0)/" -i /var/lib/dpkg/status
    } || true
}

purge_kernel(){
    VER_LONG=$(ls -d /usr/src/linux-headers-${VER/-rc/*rc}*${MODE} 2>/dev/null | sed 's/.*headers-//')
    purge_packages="$(dpkg -l | awk '{print $2}' | grep -e linux-image.*.${VER_LONG:-dummyvar} -e linux-modules-${VER_LONG:-dummyvar} -e linux-headers-${VER_LONG:-dummyvar} -e linux-headers-${VER/-rc/.*.rc})" || true
    ### TODO check if ^^^ match only one VER !!! 
    ### TODO ^^ if purge system/repository last kernel, also remove meta's: linux-generic-hwe-20.04* linux-headers-generic-hwe-20.04* linux-image-generic-hwe-20.04*
    ###		not possible without, because this is calc by apt dependencies

    [[ ${running_kernel} = ${VER_LONG} ]] && { eerror "${running_kernel} ${is_running_kernel_exiting}"; exit; }

    DST="/usr/src/linux-headers-${VER_LONG}"
    for i in scripts/basic/fixdep tools/objtool/fixdep tools/bpf/resolve_btfids/fixdep scripts/mod/modpost tools/objtool/objtool scripts/genksyms/genksyms scripts/sign-file include/config/auto.conf; do
        rmdir ${DST}/$(dirname ${i}) 2>/dev/null || true
        [[ -f ${DST}/${i}.orig ]] && { ewarn "${removing_backup_of_previous_file} ${DST}/${i}.orig"; rm -f ${DST}/${i}.orig; }
    done
    rmdir ${DST}/scripts ${DST}/tools/bpf ${DST}/tools ${DST} 2>/dev/null || true

    [[ ${purge_packages} ]] && apt-get purge ${purge_packages} || { eerror "${package_ver_not_found}"; exit; }
}

show_versions(){
    check_url_available
    is_available="$(wget -q "${URL}" -O- | grep ">v5" | sed 's/.*>v5/5/;s/\/<.*//' | sort --version-sort)"

    last_norc="$(echo "${is_available}" | grep -v rc | tail -n1)"
    last_norc_check_success="$(wget -q "${URL}/v${last_norc}/HEADER.html" -O- | grep "${ARCH}/build succeeded" || true)"
    [[ ${last_norc_check_success} ]] || is_available="$(echo "${is_available}" | sed "s/^${last_norc}$/& ${kernel_is_not_ready_yet}/")"

    [[ $2 = norc || $1 = norc ]] && { 
        is_available="$(echo "${is_available}" | grep -v rc)" 
    } || {
        last_rc="$(echo "${is_available}" | tail -n1)"
        last_rc_check_success="$(wget -q "${URL}/v${last_rc}/HEADER.html" -O- | grep "${ARCH}/build succeeded" || true)"
        [[ ${last_rc_check_success} ]] || is_available="$(echo "${is_available}" | sed "s/^${last_rc}$/& ${kernel_is_not_ready_yet}/")"
    }

    [[ $1 ]] && echo "${is_available}" | grep ^${1} ||  echo "${is_available}"
    exit 0
}

show_installed(){
    is_installed="$(dpkg -l | awk '{print $2}' | grep linux-image.*.${MODE}$ | grep -v linux-image-generic | sed 's/linux-image-signed-//;s/linux-image-unsigned-//;s/linux-image-//' | sort --version-sort)"
    [[ $1 ]] && echo "${is_installed}" | grep ^${1} || (echo  "${is_installed}" | sed "s/^${running_kernel}$/& (${running})/")
    exit 0
}

sicherboot_set_default(){
    ls /boot/efi/loader/entries/*${VER/-rc/*rc}* &>/dev/null || { eerror "${sicherboot_kernel_not_found}"; exit; }
    einfon "${set_ver_as_default_for_sicherboot}"
    read -n1 forsicher

    if [[ ${forsicher} = [y,Y,a,A] ]]; then
        ewarny "${detect_new_id_via_bootctl}"

        new_default="$(bootctl list 2>/dev/null | grep id: | grep ${VER/-rc/.*.rc} | sed 's/.*id: //')"

        ### maybe because (on my t430s) "bootctl" show "WARNING: The boot loader reports different ESP UUID then detected!" ??
        [[ ${new_default} ]] || { ewarn "${previous_detect_failed_try_default_efi_dir}"; new_default="$(basename $(ls /boot/efi/loader/entries/*${VER/-rc/*rc}*))"; }

        [[ ${new_default} ]] || { eerrorsmall "${not_detected_new_id_skipping_setting}"; return; }
        new_default_count="$(echo "${new_default}" | wc -l)"
        [[ ${new_default_count} = 1 ]] || { eerrorsmall "${ambiguous_detection_new_id_skipping_setting}"; return; }

        ewarn "${set_default_to} ${new_default}"
        bootctl set-default "${new_default}"
    fi
}

sicherboot_set_default_only(){
    which sicherboot >/dev/null && sicherboot_set_default || { eerror "${sicherboot_not_found_exiting}"; exit; }
}

show_usage(){
    einfo "Usage: $(basename $0) [s|l|i|d|n|p|b|u] [ver|latest|latest-rc|norc] <norc>"
    ewarnns "s, show \t - ${help_show_available_versions}"
    ewarnns "l, list \t - ${help_show_installed}"
    echo ""
    ewarnns "i, install\t - ${help_download_and_install}"
    ewarnns "d, download - ${help_download_only}"
    ewarnns "n, only_install - ${help_install_only}"
    ewarnns "p, purge \t - ${help_purge_kernel}"
    ewarnns "b, sicherboot - ${help_sicherboot}"
    echo ""
    ewarnns "ver \t - ${help_ver_ver}"
    ewarnns "latest \t - ${help_ver_latest}"
    ewarnns "latest-rc \t - ${help_ver_latest_rc}"
    ewarnns "norc \t - ${help_ver_norc}"
    echo ""
    ewarnns "u, upgrade - ${help_upgrade}"

    einfo "${help_information}"
    ewarnns "$(basename $0) ${help_version} ${VERSION}"
    ewarnns "${help_running_os} $(lsb_release -s -d) ($(lsb_release -s -c))"
    ewarnns "${help_running_kernel} $(uname -r)"
    ewarnns "${help_free_on} /boot:$(df -h --output=avail /boot | tail -n1)"
    [[ -d /boot/efi ]] && ewarnns "${help_free_on} /boot/efi:$(df -h --output=avail /boot/efi | tail -n1)"
    echo ""
    exit
}

kumk_upgrade(){
    kumk_url="https://raw.githubusercontent.com/k3dar/kumk/main/kumk"
    kumk_path="$(dirname $0)"
    kumk_new="${kumk_path}/kumk.new"
    einfo "${check_for_kumk_new_version}"
    wget -q  ${kumk_url} -O "${kumk_new}" && {
        diff "${kumk_new}" "${0}" &>/dev/null && {
            ewarn "${no_new_version}"
            rm -f "${kumk_new:-dummy}"
            exit
        } || {
            ewarnn "${found_new_version_upgrade_me_ask}"
            read -n1 answer

            [[ "${answer}" = [y,Y,a,A] ]] && {
                echo ""
                ewarn "${upgrading_myself}"
                chmod a+x "${kumk_new}"
                mv "${kumk_new}" "${0}"
                exit
            } || {
                ewarn "${upgrade_skipped}"
                exit
            }
        }
    } || {
        eerror "${problem_with_check_new_version}"
    }
}

set_locale

if [[ "$1" != @(s|show|l|list|i|install|d|download|n|only_install|p|purge|b|sicherboot|u|upgrade) && $1 ]]; then
    eerror "${error_unknown_main_parameter} ${1}"
    show_usage
elif [[ "$2" = "" && "$1" != "" && "$1" != @(s|show|l|list|u|upgrade) ]]; then
    eerror "${error_must_enter_version_as_second_parameter}"
    exit
elif [[ "$2" = "latest" && "$1" != @(s|show) ]]; then
    tmp_ver="$(show_versions | grep -v rc | tail -n2 | sed 's/^v//;s/ (.*//')"
    VER="$(echo "${tmp_ver}" | tail -n1)"
    VER_PREV="$(echo "${tmp_ver}" | head -n1)"
elif [[ "$2" = "latest-rc" && "$1" != @(s|show) ]]; then
    tmp_ver="$(show_versions | tail -n2 | sed 's/^v//;s/ (.*//')"
    VER="$(echo "${tmp_ver}" | tail -n1)"
    VER_PREV="$(echo "${tmp_ver}" | head -n1)"
elif [[ "$1" != @(s|show) ]]; then
    VER="$(echo ${2} | sed 's/-generic//;s/-lowlatency//;s/*//g')"
fi

(echo ${VER}      | grep -q '^[0-9]\+\.[0-9]\+$')    && { VER_NOZER="${VER}";           VER="${VER}.0"; }
(echo ${VER_PREV} | grep -q '^[0-9]\+\.[0-9]\+$')    && { VER_PREV_NOZER="${VER_PREV}"; VER_PREV="${VER_PREV}.0"; }
(echo ${VER}      | grep -q '^[0-9]\+\.[0-9]\+\.0$') &&   VER_NOZER="${VER/.0}"
(echo ${VER_PREV} | grep -q '^[0-9]\+\.[0-9]\+\.0$') &&   VER_PREV_NOZER="${VER_PREV/.0}"

set_locale
detect_arch
running_kernel="$(uname -r)"

case $1 in
    's'|'show') 	show_versions $2 $3 ;;
    'i'|'install') 	download_kernel && install_kernel ;;
    'd'|'download') 	download_kernel ;;
    'n'|'only_install') install_kernel ;;
    'p'|'purge') 	purge_kernel ;;
    'l'|'list') 	show_installed $2 ;;
    'b'|'sicherboot')	sicherboot_set_default_only ;;
    'u'|'upgrade')	kumk_upgrade ;;
    *) show_usage ;;
esac

einfo "${finish}"
 